# The URL the site will be built for
base_url = "https://mhpark.me"
title = "Mike's Blog"
description = "The personal, rarely updated, blog of Michael Park"

# Compile all Sass files in sass/
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]

[markdown.highlighting]
theme = "github-dark"
style = "class"

[extra]
email = "webmaster@mhpark.me"
base_url = "https://mhpark.me"
default_language = "en"

menu = [
    { name = "posts", url = "posts", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "about-me", url = "about-me", trailing_slash = false },
]

socials = [
    { name = "bluesky", url = "https://bsky.app/profile/mhpark.me" },
    { name = "github", url = "https://github.com/KingMichaelPark/" },
    { name = "hacker-news", url = "https://news.ycombinator.com/user?id=Zizizizz" },
    { name = "mastodon", url = "https://fosstodon.org/@mdawg" },
]

[extra.author]
name = "Michael Park"
avatar = "me512.png"
