# The URL the site will be built for
base_url = "https://mhpark.me"
title = "Mike's Blog"
description = "The personal, rarely updated, blog of Michael Park"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = true

theme = "tabi"
taxonomies = [
    # You can enable/disable RSS
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
skin = "sakura"
menu = [
    { name = "posts", url = "posts", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
]

[extra.author]
name = "Michael Park"
avatar = "me512.png"

# Social links
[extra.social]
email = "webmaster@mhpark.me"
github = "KingMichaelPark"
keybase = "mparkypark"
linkedin = "michael-h-park"
mastodon_username = "mdawg"
mastodon_server = "fosstodon.org"
bluesky_username = "mhpark.me"
