# The URL the site will be built for
base_url = "https://mhpark.me"
title = "Mike's Blog"
description = "The personal, rarely updated, blog of Michael Park"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = true

theme = "tabi"
taxonomies = [
    # You can enable/disable RSS
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
email = "webmaster@mhpark.me"
skin = "sakura"
menu = [
    { name = "posts", url = "posts", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "about-me", url = "about-me", trailing_slash = false},
]
socials = [
    { name = "bluesky", url = "https://bsky.app/profile/mhpark.me", icon = "bluesky" },
    { name = "github", url = "https://github.com/KingMichaelPark/", icon = "github" },
    { name = "hacker-news", url = "https://news.ycombinator.com/user?id=Zizizizz", icon = "hacker-news" },
    { name = "mastodon", url = "https://fosstodon.org/@mdawg", icon = "mastodon" },
]


[extra.author]
name = "Michael Park"
avatar = "me512.png"

# Social links

